### ISSUE TITLE
Java 21 support

### ISSUE THREAD

**Issue by optodent** [spring-projects/spring-guice#115]
Migrating from Java 17 to Java 21, I have experienced guice modules compiled with java 21 incompatible with spring-guice:2.0.4 getting the following error during compile time: `Unsupported class file major version 65`. Going back to java 17 for the specific modules the compilation was successful.

Raising this as 21 is the latest LTS release.

**Comment by sblommers** [comment]
This probably means also updating to Guice 6.0.0 (for javax.inject + jakarta.inject) or Guice 7.0.0 (for jakarta.inject).

We currently pin to Guice 6.0.0 for spring-guice to work correctly because it only knows javax.inject package.

Another option could be to use com.google. packages only and let Guice figure out what to do with JSR-330

**Comment by dsyer** [comment]
FWIW it works for me with Guice 6.0.0, so you should be able to make that change yourself locally. See also #117 (would obsolete and move directly to Guice 7.0.0).

**Comment by dsyer** [comment]
Closed (obsolete) now that 3.0.0 is available. Note: you can still use Guice 6.0.0 with the 2.0.x releases
