### ISSUE TITLE
Configuration class enhancement does not work

### ISSUE THREAD

**Issue by avmohan** [spring-projects/spring-guice#75]
Warning messages of below form are printed to the console.

> INFO  org.springframework.context.annotation.ConfigurationClassPostProcessor - Cannot enhance @Configuration bean definition 'testConfiguration' since its singleton instance has been created too early. The typical cause is a non-static @Bean method with a BeanDefinitionRegistryPostProcessor return type: Consider declaring such methods as 'static'. 

CgLib proxying of `@Configuration` class objects does not work since their instances are created too early. As a result the special behavior on the `@Bean` methods don't work. Is this a known limitation?

**Comment by dsyer** [comment]
It might be. Maybe you could describe your use case in more detail? Post some code or refer to a test case in the project?

**Comment by avmohan** [comment]
Sorry I don't have any context on this any more as this was around 2 years back

**Comment by dsyer** [comment]
I saw a bunch of those warnings when I ran the tests today, so I don't think it has gone away. Probably needs some care isolating the issue.

**Comment by simondemartini** [comment]
Is this is due to `Module` beans being initialized with the `getBeansOfType(Module.class)` here? https://github.com/spring-projects/spring-guice/blob/c22fb6a976875abd006d2bff9e82a8a934bc1a03/src/main/java/org/springframework/guice/annotation/ModuleRegistryConfiguration.java#L105

If we can't get rid of that early init, would it be reasonable to just log a more clear warning to recommend that `Module` beans are created with static bean methods like the original spring warning posted above?

**Comment by dsyer** [comment]
We can't fix this, but we can document the limitations. I cleared up all the tests and added a paragraph to the README in c22fb6a.
